### ISSUE TITLE
No help icon displayed in Krumo

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/devel#1]
The help icon at the bottom of Krumo displays is missing. The path it's looking for is '/misc/help.png' whereas it should be '/core/misc/help.png'.

**Comment by quicksketch** [comment]
Thanks @BWPanda! I didn't have notifications on here in devel.module so I missed this. I just completed a full port of Devel (with config management) and ran across this as well. I deleted the "master" branch and put up a "1.x-1.x", so it closed the PR, but I added it back in manually. Thanks!
