### ISSUE TITLE
Update krumo to at least 0.4.1

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/devel#102]
This was recommended in https://github.com/backdrop-contrib/devel/issues/101 but I couldn't get it to work.

Devel is currently using version 0.2.1a, which includes the function `krumo::addCssJs()`. We are using this function to attach the CSS and JS from krumo on the second page load, where the messages will be printed if `dpm()` is called after the messages area is already rendered on the current page. 

The code comment in our module is as follows:
```php
    // If dpm() is called after status messages have been rendered, they will
    // instead appear on the next page load. So ensure the krumo CSS and
    // Javascript files are included.
```

I attempted simply removing the call to `krumo::addCssJs()` to see what would happen, but the expandable elements not only turned out very ugly, but they wouldn't expand. 

I don't understand why `krumo::addCssJs()` was removed in later versions, or what the recommended alternative might be (I checked the release notes and change logs but didn't see anything relevant), so I've instead added a patch to the old `0.2.1a` version of krumo in devel so that I can keep working until we figure it out :)

**Comment by ghost** [comment]
It seems Devel has hacked Krumo and changed a bunch of stuff in Krumo's files - including adding the `addCssJs()` function.

Here's a diff I made of Krumo v0.2.1a downloaded from their GitHub repo, and Devel's copy (`diff -uprwiNEB --ignore-file-name-case krumo-0.2.1a/ krumo/`): [krumo.diff.txt](https://github.com/backdrop-contrib/devel/files/5473715/krumo.diff.txt)

**Comment by ghost** [comment]
Here's a PR that updates to the new version: https://github.com/backdrop-contrib/devel/pull/134

I simply replaced the Krumo library with the updated one, then commented out the lines in `devel.module` that caused issues, and hard-coded the `default` skin.

There's obviously more work to do here, like deciding what removed customisations are still needed (and working out how to add them back in, preferably without hacking Krumo again).

**Comment by jenlampton** [comment]
I was so excited that I merged this. I'm not sure that was the best idea, but I'm going to give it a try. I've also created a follow-up issue to address all the things we still need to do: https://github.com/backdrop-contrib/devel/issues/135

**Comment by jenlampton** [comment]
Note that this has been removed from 1.x-1.x until we can resolve some of the related errors, and is now in a PR for https://github.com/backdrop-contrib/devel/issues/135
