### ISSUE TITLE
Web page (dpm()) slowing down browser

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/devel#104]
Sometimes when I use `dpm()` to view an object/variable, I get a message in my browser saying that a web page is slowing down the browser:

![2020-11-27_10-40](https://user-images.githubusercontent.com/2385329/100397356-59d40d00-309d-11eb-904c-7e70bd4d05c3.png)

Even though I click the 'Wait' button, the message often keeps appearing. If the page does eventually finish loading, the `dpm()` output often doesn't work (i.e. you can't click on it to expand/navigate the results).

I have a fairly new and powerful computer, so I don't think it's that.

Here are some steps to (kind of) reproduce the problem:

- Spin up a new Backdrop site (e.g. a Backdrop Demo site)
- Install the Devel module
- Go to Development > Information > Theme Registry (`/admin/devel/info/theme`)

For me, as the page is loading my computer fan gets louder (indicating it's doing extra processing) and the message appaers as per the screenshot above. However, unlike other times I've experienced this, the message will go away on its own if I do nothing and the page will eventually load and display correctly.

But I believe there is some underlying issue here, and I'd love to get it fixed so I can use `dpm()` without issue...

**Comment by ghost** [comment]
I just found a topic where I had previously complained about this issue in Zulip, and when I used `dd()` to output the variable to a file instead of the screen, the file was 400MB in size.

So I guess I'm asking if there's a way Devel/`dpm()` can output maybe just the top level or so of a large array/object, instead of trying to output the whole thing and causing these issues.

Drupal 8's `kint()` function has a setting where you can tell it to output only so many levels. Maybe that'd be handy here too...?

**Comment by bradbulger** [comment]
I'm seeing something like this, trying to dpm($form) in a validation function, pretty normal. Chrome loads and loads until it finally crashes. I tried walking through each item in the form array, but it's not clear where the slowdown is coming from. The last field that's visible is a long text field, which does have recursive references, but I'd already displayed a dpm() result for one above. Maybe they were all loading still, not sure how to tell. (I ended up displaying a print_r() of the values, which bails on recursions - not ideal but better than nothing.)

**Comment by jenlampton** [comment]
PHP's `debug_backtrace()` has a similar parameter that allows for a level of nesting.

I often use `dpm(array_keys($variable));` when I know the variable I'm printing is deep -- to get only the first level. 

It would be nice if the default for `dpm()` was something like 4 or 5 levels deep, but if we do figure out how to truncate the nesting somehow, it would be important that we have some way to tell that there are further values we just can't see.

**Comment by argiepiano** [comment]
I'm seeing the same issue. Just for comparison, I'm trying to output exactly the same in both Drupal 7 and Backdrop using dpm. It is a complex structure; however, D7 is able to output it in about 5 seconds. Backdrop never does - the browser keeps spinning and asking to terminate.

While outputting the array keys is a neat trick, it doesn't always work well.  It would be great if dpm worked as it did in D7. I'm wondering if some of the recursion control in Backdrop is just not working, throwing things into huge loops that get impossibly large when the structures are complex?

**Comment by jenlampton** [comment]
Maybe @hosef can help us with this one?

**Comment by argiepiano** [comment]
I've done a bit of digging. The server side processing of the dpm structure is very fast - that's not the issue. It's the browser side processing that's taking a crazy amount of time in Backdrop. 

See these two screen captures for comparison. I did a `dpm(theme_get_registry());` both in Drupal 7 and Backdrop 1.21.0 running in the same environment. 

The images below show that Backdrop took 21,700 milliseconds (21 seconds!!!) just for "Scripting", which is the JS processing that happens after the page is delivered to the browser. 

In contrast, for the same output, D7 took 139 milliseconds (0.1 second). 

There is something wrong with the scripting that goes on after the page delivery of a complex dpm output, and I suspect it's the Krumo script or something above it that's creating this issue. Or it could be that there is something wrong with the html output produced by Krumo that's making the scripting very time consuming.

I don't have the JS or jQuery expertise to troubleshoot this. Wondering if anyone is inclined to do so? dpm is SUCH a basic debugging tool, and not being able to out, for example, views objects, severely limits its usefulness.

D7
<img width="1440" alt="Screen Shot 2022-01-21 at 2 05 18 PM" src="https://user-images.githubusercontent.com/9938978/150600680-20fa0381-7337-497c-ac3f-a63eab360c69.png">

Backdrop
<img width="1440" alt="Screen Shot 2022-01-21 at 2 06 27 PM" src="https://user-images.githubusercontent.com/9938978/150600720-ac02e6c5-eff7-421a-ad33-7087086543a6.png">

**Comment by argiepiano** [comment]
I have done some additional comparisons after @BWPanda suggested this in Zulip.

The output of `theme_get_registry()` is similar in both Drupal 7 and Backdrop: 142Kb in D7,  139Kb in Backdrop.

I also compared the HTML output of kprint_r, which is the function that dpm uses to produce the markup. Again, very similar in both:  940Kb for Drupal, and 882Kb for Backdrop.

To me, this suggests that, as suspected from the benchmark measures above, the problem is in the JS processing of the markup done in the browser - the krumo script in Backdrop is taking 150 times longer to create the same output than the Drupal one. Both are running in PHP 7.4.

**Comment by ghost** [comment]
Not sure if this is related, but it probably doesn't help that we're using an ancient version of Krumo: https://github.com/backdrop-contrib/devel/issues/102

**Comment by ghost** [comment]
@argiepiano Can you please try the PR in https://github.com/backdrop-contrib/devel/issues/102 (which updates Krumo to the latest version) and see how that performs against your previous tests? It seems much snappier to me...

**Comment by argiepiano** [comment]
@BWPanda I'm happy to report that, with the PR you made (which @jenlampton merged already into the dev version) `theme_get_registry()` is now built and shown at blazing speed!  I haven't tested other dumps, but this was one that took over 20 seconds, now shown in 2 seconds. Thanks!

**Comment by ghost** [comment]
@argiepiano Great news! Shall we close this issue as 'fixed' then, or did you want to do more testing?

**Comment by argiepiano** [comment]
@BWPanda the new merged PR, when it works, solves the issue of speed, so, yes, we could close this.

The PR, however, creates other issues. See #135. I will open another issue as well that I just found. So, while the speed is not a problem now, there are others more serious issues with the new PR.

**Comment by ghost** [comment]
OK, closing this then.

Fixed in https://github.com/backdrop-contrib/devel/issues/102
