### ISSUE TITLE
Request for co-maintainership

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/devel#113]
I believe Nate has no time as the issue queue shows lot's of good, but uncommitted PRs. And because this module is essential in developing Backdrop websites, we have to maintain another fork of the module with committed PRs. Which is not ideal.

The README says the module is seeking additional maintainers. Please add me as a co-maintainer, so I could push number of necessary PRs in.

**Comment by jenlampton** [comment]
@alanmels thanks for your interest in helping to maintain devel!  I, for one, would love to see you as a co-maintainer. :) I've also been applying patches to devel on each of my sites, and I agree it's a hassle.

> Please add me as a co-maintainer, so I could push number of necessary PRs in.

Could you please file a PR that adds your name to the readme, and place a link to the PR from this issue? 

> The README says the module is seeking additional maintainers. 

Filing a PR will make it easy for any of the current maintainers to merge your PR and make you a co-maintainer right away. 

If none of them respond after a period of two weeks, then the Bug Squad would also be able to merge your PR to add you as a co-maintainer. I hope it won't come to that, but if it does, please create an issue in the [contrib queue](https://github.com/backdrop-ops/contrib/issues) to get the attention of the Bug Squad.

**Comment by jenlampton** [comment]
I just went through the list of PRs to see if anything there qualified for a Bug Squad merge today, but nothing there has been tested and approved yet.

**Comment by jenlampton** [comment]
PR merged by bug-squad. @alanmels you are now a co-maintainer for devel!
