### ISSUE TITLE
Add devel tabs to the File entity pages

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/devel#115]
Users, nodes, taxonomies, and contents all have a "Devel" tab with "Load" and "Render" subtabs.  Managed files could have the same under `file/%file/devel`.

**Comment by jlfranklin** [comment]
All it needs are the menu router entries.

**Comment by jenlampton** [comment]
Fixed via https://github.com/backdrop-contrib/devel/pull/117
