### ISSUE TITLE
Allow debugging during Backdrop core Simpletest

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#120]
This is basically the same as https://www.drupal.org/project/devel/issues/852194

That issue was originally about introducing a new `sdpm()` function, but the latest patches provided there tweak `devel.module` to allow the existing `dpm()` function to output its results in the tests results summary, the same way as the `debug()` function does.

I was able to patch the Backdrop version of the module with the patch provided for Devel 7.x in https://www.drupal.org/project/devel/issues/852194#comment-3381552, and it seems to be working great:

![image](https://user-images.githubusercontent.com/2423362/117528328-55ac0400-afda-11eb-97ec-c91cf439452a.png)

**Comment by klonos** [comment]
Related discussion in Zulip: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Debugging.20tests/near/235053706

@klonos 
> klonos: I use the Devel module and `dpm()` very heavily. ...but how do I debug simpletests?
> 
> ...and has anyone used anything like https://www.drupal.org/project/tlds or https://www.drupal.org/project/dbase_dpm?

@indigoxela 
> I never use dpm(), I always use debug() directly and that also works in tests. https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/debug/1

@oadaeh 
> oadaeh (Jason Flatt): debug() and dpm() operate in the same way. If dpm() doesn't work, chances are debug() will not either.
> 
> oadaeh (Jason Flatt): When dpm() doesn't work for me, I use watchdog() as an alternative, but I think with tests, that might not work, if the database gets cleaned up. I think you might have to use xdebug and put in breakpoints to catch and watch the execution as it's happening.

@klonos 
> `debug()` actually seems to be working well (for simple things at least):
> ![image](https://user-images.githubusercontent.com/2423362/117528609-b5ef7580-afdb-11eb-82c6-b23bd58fa4a1.png)
> `...dpm()` doesn't output anything.

@hosef 
> `debug()` is integrated into Simpletest so that it always puts it into the test log. `dpm()` puts it in messages the next time a page is rendered, so you would have to get a page and then look at it inside the test run. You would also need to enable devel in the test run.

@oadaeh 
> Joseph has schooled me in the ways of debug(). 😅  I had no idea it was so integrated in the code base. I thought it was just an external function call for displaying info, like dpm() is.

@klonos 
> > You would also need to enable devel in the test run.
>
> Right! ....I should have thought of that.

@indigoxela 
> > debug() and dpm() operate in the same way. If dpm() doesn't work, chances are debug() will not either.
>
> Not at all. I'm using debug() in tests several years now. The devel module doesn't provide much help within automated tests, debug() is fully usable.

**Comment by klonos** [comment]
PR here: https://github.com/backdrop-contrib/devel/pull/121

**Comment by klonos** [comment]
@quicksketch or @alanmels can you please review and merge this? I have been using it on my local w/o issues since May.

**Comment by bugfolder** [comment]
I tried this out by applying this PR to a local test site and found a reproducible failure. To reproduce, in file `dashboard.test` in function `testDashboardLayout()`, add the following lines at the top:

```
  function testDashboardLayout() {

    $foobar = array('foo' => 'Foo', 'bar' => 'Bar', );
    dpm($foobar, '$foobar');

    $account = user_load(1);
    dpm($account, '$account');

    dpm($this,'$this');
    ...
```

Then run the Dashboard test. (There's nothing special about the Dashboard test; I'm just using it to host the test code.) In the test, the first two `dpm()` calls work fine, properly rendering the array and the object, but the third `dpm($this...)` breaks the test.

The first time I tried this, it completely hosed the site (db error generated on every page load attempt), but after trying it again on a fresh install, it's possible to cleanup after the failed test and re-run things. Commenting out the `dpm($this,...)` works fine.

**Comment by docwilmot** [comment]
Will the test need to add devel module to `setup()`?

**Comment by bugfolder** [comment]
I think if tested automatically, it needs to be added. When testing using the real-time testing (via /admin/config/development/testing), it wasn't necessary (but I had devel enabled on the test site). Adding it to `setup()` doesn't affect the success and error described above.

**Comment by klonos** [comment]
🤔
