### ISSUE TITLE
Warning: mt_rand(): max(0) is smaller than min(1) if max comments is set to 0

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#123]
When generating nodes with the "Maximum number of comments per node." setting set to 0, I receive this warning multiple times:

```
Warning: mt_rand(): max(0) is smaller than min(1) in devel_generate_add_comments()
(line 155 of /app/docroot/modules/devel/devel_generate/devel_generate.inc).
```

**Comment by klonos** [comment]
@alanmels or @quicksketch can you please review/merge this simple fix? Thanks.

**Comment by bugfolder** [comment]
Tested on a local site: works as advertised. LGTM.
