### ISSUE TITLE
"Show query arguments" configuration is not saved

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/devel#139]
The admin/config/development/devel page shows a configuration for "Show query arguments", but the setting isn't saved when the "Save Configuration" button is clicked.

After checking the "Show query arguments" box and saving, I checked the configuration file and there is no entry for "show_query_args_first". If I manually add this line to the configuration file ("show_query_args_first": true,), the query arguments are shown.

I noticed that devel_admin_settings_submit() in devel.admin.inc doesn't include a $config->set for "show_query_args_first".

**Comment by herbdool** [comment]
I can confirm this.

**Comment by herbdool** [comment]
I added a PR. @jenlampton @alanmels @kswan
