### ISSUE TITLE
Include ability to generate entity reference fields 

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/devel#140]
Now that entity reference is in core could include https://git.drupalcode.org/project/entityreference/-/blob/7.x-1.x/entityreference.devel_generate.inc here.

**Comment by herbdool** [comment]
I've got a simple PR ready - it simply moves the old code from entity reference module to here and allows it to be used. Worked for me in testing.

@jenlampton @alanmels

**Comment by alanmels** [comment]
@herbdool These days no time for Backdrop, and I usually do not interfere with the development of this module, however trusting your expertise just noticed this and decided to merge.
