### ISSUE TITLE
Invalid option source in Sort query log element

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/devel#144]
**Steps to reproduce**
1. Start from new install of Devel or disable and uninstall then re-enable
2. Open Devel settings
3. Leave Display query log as unchecked and change another setting (e.g. Enable theme debug)
4. Save

**Expected result**
Settings save

**Actual result**
Error message: Invalid option source in Sort query log element.
Now, if we click on Display query log we see this:
![image](https://user-images.githubusercontent.com/20357797/203549054-000fea4e-8d8b-49d2-b010-0ee8404cecf0.png)

**Comment by yorkshire-pudding** [comment]
@jenlampton @quicksketch @alanmels 

I've added a PR for this issue - please review.

**Comment by alanmels** [comment]
On a fresh Backdrop setup with Devel it shows "by source" selected by default as soon as I check on the "Display query" log option:

![Screenshot 2022-11-23 at 10 28 17 AM](https://user-images.githubusercontent.com/56604405/203598588-6a8157e3-5bbb-43ad-9731-8d74c56f55bd.png)

**Comment by yorkshire-pudding** [comment]
Works on PHP 7.4; does not work on PHP 8.1 (or PHP 8.0)

I don't know why it works on 7.4 as the code isn't clear.

The default config: `config/devel.settings.json` says :
```json
"query_sort": "source",
```

`devel.module` has this as the constant values:
```php
define('DEVEL_QUERY_SORT_BY_SOURCE', 'source');
define('DEVEL_QUERY_SORT_BY_DURATION', 'duration');
```

`devel.admin.inc` defines the radio buttons as:
```php
  $form['queries']['settings']['query_sort'] = array(
    '#type' => 'radios',
    '#title' => t('Sort query log'),
    '#default_value' => $config->get('query_sort', DEVEL_QUERY_SORT_BY_SOURCE),
    '#options' => array(t('by source'), t('by duration')),
    '#description' => t('The query table can be sorted in the order that the queries were executed or by descending duration.'),
  );
```
This results in markup of:
```html
<div class="form-item form-type-radios form-item-query-sort">
  <label for="edit-query-sort">Sort query log </label>
  <div class="form-radios" id="edit-query-sort">
    <div class="form-item form-type-radio form-item-query-sort">
      <input type="radio" id="edit-query-sort-0" name="query_sort" value="0" checked="checked" class="form-radio" /> <label class="option" for="edit-query-sort-0">by source </label>
    </div>
    <div class="form-item form-type-radio form-item-query-sort">
      <input type="radio" id="edit-query-sort-1" name="query_sort" value="1" class="form-radio" />  <label class="option" for="edit-query-sort-1">by duration </label>
    </div>
  </div>
  <div class="description">The query table can be sorted in the order that the queries were executed or by descending duration.</div>
</div>
```

As you can see the radio values are 0 and 1. As 1 being 'by duration' then you might expect it to evaluate 'source' truthly and select that, though it doesn't on 7.4 and instead selects 0.  As you can see from the screenshot taken from 8.1, it fails to select any.  I have confirmed the same behaviour on 8.0.

The PR sets the constant values as the array keys so when it looks for 'source' then it will find it.

Currently, the radio buttons set the value in config to 0 or 1
```json
"query_sort": "1",
```
That doesn't seem logical: source/duration is not a boolean equivalent.

I'm not quite sure which change in PHP 8 causes this but I have reproduced multiple times.

**Comment by alanmels** [comment]
You're right - I was failing to replicate the problem because I was testing it on a system with PHP 7.4. Re-launching the environment on PHP 8.1 confirmed the problem and the validity of the fix. Thank you.
