### ISSUE TITLE
PHP 8.2: Deprecated function: Implicit conversion from float to int loses precision in devel_generate_word()

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#156]
I got a series of deprecation errors when trying to generate users in PHP 8.2:

> Deprecated function: Implicit conversion from float 251518.00000000003 to int loses precision in devel_generate_word() (line 477 of /app/docroot/modules/devel/devel_generate/devel_generate.inc).

![image](https://github.com/backdrop-contrib/devel/assets/2423362/c157b302-445f-4d10-9c98-e99f83e05142)

**Comment by klonos** [comment]
This simple change fixes things for me: https://github.com/backdrop-contrib/devel/pull/157 (although not 100% sure whether it's the best approach)

**Comment by laryn** [comment]
@klonos Is this one related?
https://gitlab.com/d7security/devel/-/merge_requests/1

**Comment by klonos** [comment]
Other than the fact that both are related to issues with various php versions, I don't think so @laryn. This one is explicitly about php v8.2 and the specific error. ...but we should merge the changes in that other issue as well if they apply to he Backdrop version (in another issue though - I'm assuming that there must be other cross-ports that might apply to us as well).

**Comment by klonos** [comment]
...this one is the same though: https://gitlab.com/d7security/devel/-/commit/c663b69f7b3b36adc08e02e22f9c17c6452fa184. It is the same compared to my PR, but they also fixed some coding standards issues as well. I'll apply the same to my PR shortly.
