### ISSUE TITLE
Add devel icon to admin_bar

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/devel#158]
Backdrop now has an Icon API! Let's add `code-fill` icon to the menu. https://phosphoricons.com?q=%22code%22&weight=%22fill%22

**Comment by herbdool** [comment]
I've added a PR. It's backwards-compatible. If someone is on an older version of Backdrop the `icon` will just get ignored.

**Comment by indigoxela** [comment]
Like it! :smile: 

Here's a little before/after screenshot for comparison:

![before-after](https://github.com/backdrop-contrib/devel/assets/842066/f4ae9a4f-c7d2-4016-aabb-5ed4041e2fa5)
