### ISSUE TITLE
[UX] Devel Generate: Generate terms: Switch to checkboxes and use vocabulary names/labels instead of their machine names.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#19]
UX WTF! Steps to reproduce:
1. Generate a few vocabularies via the "Generate vocabularies" tab (`/admin/config/development/generate/vocabs`).
2. Head to the "Generate terms" tab (`/admin/config/development/generate/taxonomy`). Don't like the names of the vocabularies generated in step 1 above.
3. Go to the vocabularies admin page (`/admin/structure/taxonomy/list`) and rename the vocabularies.
4. Return to the "Generate terms" tab: vocabularies names still not changed. WTF?!
5. Hover over the admin bar at Structure -> Taxonomy: vocabularies are shown with their new names. Double WTF?!
6. Realize that the "Generate terms" tab uses the vocabularies machine names and have an AHAH!! moment (if you know Drupal/Backdrop).

Lets change it so that the actual vocabularies names/labels are used instead and while at it, also switch the select box to checkbox list too...

**Comment by quicksketch** [comment]
I merged in the first PR, which switches to using the vocabulary label instead of the machine name. I'll leave this issue open if you'd like to follow-up to switch to checkboxes.

**Comment by klonos** [comment]
Thanx @quicksketch.

I'll see how good my code-fu is and file a separate PR for the checkbox.

**Comment by quicksketch** [comment]
I switched the options to a checkbox. It didn't seem to require any further changes other than changing `#type`. I'll be make a new release, let's reopen this issue if we have any regressions.
