### ISSUE TITLE
Add description to 'Execute PHP' block

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/devel#23]
After the kerfuffle with the 'Execute PHP' block in https://github.com/backdrop/backdrop-issues/issues/1891 I recommend adding a description to this block to better explain what it does (e.g. "Allows PHP code to be entered and executed wherever this block is rendered.").

**Comment by ghost** [comment]
![firefox_screenshot_2016-05-18t06-59-56 674z](https://cloud.githubusercontent.com/assets/2385329/15350106/b4e7251a-1d1a-11e6-9077-032211b2ff03.png)
(nothing currently)

**Comment by quicksketch** [comment]
Great idea, thanks! Agreed, all blocks should have a description, especially one as dangerous as this one.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/devel/commit/4d0617f5e3c8e502a4f0ad96b4611b881fd1f08c. Thanks @BWPanda!

**Comment by klonos** [comment]
Thanx @quicksketch ...minor nit: the parts of the text that you've wrapped with `<code>` tags would be better off with `<i>` tags and their first letter capitalized I believe. Follow-up PR 😉

**Comment by quicksketch** [comment]
Thanks, minor PR updates merged as well.
