### ISSUE TITLE
Functions missing from devel.drush.inc

### ISSUE THREAD

**Issue by Gormartsen** [backdrop-contrib/devel#24]
Hi guys,

@quicksketch I checked drush.inc file changeling and noticed that you did change it year ago.

Specially you removed callback from generate functions.

Did you do it for purpose or is there just typo?

**Comment by quicksketch** [comment]
Hey Gor, I didn't mean to remove devel generate support. The file is still there but I admit I haven't checked on whether it works. Would be happy to fix/merge support if it is broken.

**Comment by klonos** [comment]
I am working on cross ports from 7.x. I have found the following to be missing:

- `drush_devel_download()`

**Comment by quicksketch** [comment]
Thanks @klonos. Turns out I removed `drush_devel_download()` because we just bundle FirePHP directly with Devel module, so there's no need to ever download it manually. I'll remove that Drush command since it does not serve any purpose.

**Comment by quicksketch** [comment]
This should be fixed in https://github.com/backdrop-contrib/devel/pull/95.

I tried generating content, users, terms, menus, and vocabularies all through the drush commands. e.g.

```
❰nate❙~/Sites/backdrop/modules/devel(git✱1.x-1.x)❱✔≻ lando drush genc 10
Finished creating 10 nodes                                                                                                                                                                                                                           [status]
Generated 10 nodes, 0 comments (or less) per node.                                                                                                                                                                                                   [success]
❰nate❙~/Sites/backdrop/modules/devel(git✱1.x-1.x)❱✔≻ lando drush gent tags
Created the following new terms:                                                                                                                                                                                                                     [status]
  * crupuvitho
  * nejifriphush
  * lisl
  * sus
  * clakulo
  * chimuder
  * chuwrip
  * sliwruwruru
  * geswedripho
  * dr

Generated 10 terms.
```
