### ISSUE TITLE
devel_node_access attempts to access the block table to determine who can view the block

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/devel#29]
The issue is on line 471 of `devel_node_access.module`:

```
if (!isset($block1_visible)) {
    $block1_visible = db_query("SELECT status FROM {block} WHERE module = 'devel_node_access' AND delta = 'dna_user' AND theme = :theme", array(
      ':theme' => $theme_key,
    ))->fetchField();
```

This will need to be changed to check the layout instead. Or is it needed at all? Doesn't the layout figure out itself if it should be visible to whom on that view?

**Comment by quicksketch** [comment]
Thansk @herbdool and @robertgarrigos. I removed that check since it's a lot less applicable in Backdrop due to Layouts. Fixed in https://github.com/backdrop-contrib/devel/pull/96.
