### ISSUE TITLE
Devel node access throws notices on every form submit

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/devel#3]
> If I enable ‘Devel node access’ and navigate to /admin/content I get ‘NOTICE: UNDEFINED INDEX: DEBUG_MODE IN /USERS/GEOFF/SITES/BACKDROP/MODULES/CONTRIB/DEVEL/DEVEL_NODE_ACCESS/DEVEL_NODE_ACCESS.MODULE ON LINE 108’

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/devel/commit/a5321a681614370dc5228357dc3e37927d3c467d.

**Comment by serundeputy** [comment]
cool; so if  I do another pull from this repo I'll get that?

**Comment by serundeputy** [comment]
yep; pull fixed it; sorry to clutter your issue queue.

**Comment by quicksketch** [comment]
No problem! We also made another official release (1.5.1): https://github.com/backdrop-contrib/devel/releases

Thanks for reporting it (in IRC) in the first place. :smile:
