### ISSUE TITLE
'Access Denied' when trying to switch user account

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/devel#36]
When I go to Development > Switch User Account, then enter a user's name and click Switch, I get taken to a page with an 'Access Denied' message. The URL of this page is: /admin/devel/switch/[USER NAME]?destination=&token=[RANDOM STRING]

I believe the issue lies with the `_devel_switch_user_access()` function in devel.module, as I can return TRUE from that function and it works correctly then.

---

PR by @docwilmot: https://github.com/backdrop-contrib/devel/pull/81

**Comment by ghost** [comment]
@docwilmot's PR works for me! https://github.com/backdrop-contrib/devel/pull/81

**Comment by AlexShapka** [comment]
This is to confirm that #81 also worked for me. Thanks!

**Comment by alanmels** [comment]
Unfortunately, this issue persists for me with the latest HEAD. Comparing the existing code with https://github.com/backdrop-contrib/devel/pull/81/commits/2de2e0e5c7217f057c600d1f33170559e3c1dcec I see that the line 266:

```
return user_access('switch users') && backdrop_valid_token(@$_GET['token'], "admin/devel/switch/$name|", TRUE);
```

is slightly different than what was proposed by the patch:

```
return user_access('switch users') && backdrop_valid_token(@$_GET['token'], "admin/devel/switch/$name|" . @$_GET['destination'], TRUE);
```

However, trying both didn't work.

**Comment by quicksketch** [comment]
Looks like an extra pipe character was accidentally added in the PR. After removing it, the form works correctly: bb5584e

I'm working on making a new release. If this still exists in 1.8.0 please reopen.
