### ISSUE TITLE
Devel Node Access doesn't have hook_config_info

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/devel#38]
As [reported in the forum](https://forum.backdropcms.org/comment/571#comment-571).

@quicksketch you are listed as maintain of `devel`, I assume that means you maintain `devel_node_access`, too (despite the README saying there is no maintainer for `devel_node_access`)?

**Comment by quicksketch** [comment]
Thanks @laryn! Fixed in your PR at https://github.com/backdrop-contrib/devel/pull/39.
