### ISSUE TITLE
Make "The theme registry is being rebuilt on every request." a warning.

### ISSUE THREAD

**Issue by findlabnet** [backdrop-contrib/devel#40]
devel/devel.module line 390:

-- backdrop_set_message(t('The theme registry is being rebuilt on every request. Remember to <a href="!url">turn off</a> this feature on production websites.', array("!url" => url('admin/config/development/devel'))));

++ backdrop_set_message(t('The theme registry is being rebuilt on every request. Remember to <a href="!url">turn off</a> this feature on production websites.', array("!url" => url('admin/config/development/devel'))), 'warning');

---
PR by @klonos: https://github.com/backdrop-contrib/devel/pull/41

**Comment by quicksketch** [comment]
Thanks, fixed in https://github.com/backdrop-contrib/devel/commit/f2427a0c88d6c425584206a87331c1ea1d50f8c8
