### ISSUE TITLE
Duplicate "Development" menu item in admin bar

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#43]
<img width="350" alt="screen shot 2019-01-04 at 8 21 10 pm" src="https://user-images.githubusercontent.com/2423362/50703949-680a8180-105e-11e9-8084-70311783f7e8.png">

So there is `/admin/config/development/devel` (under "Configuration"), but also `/admin/devel/settings` (top-level), which both lead to the same page.

Not entirely sure, but I believe that this started happening after [these changes](https://github.com/backdrop-contrib/devel/commit/832883c277a59f7348526a3418347a5478ad1eb8#diff-98396f7e1b366bc191b3fd214cd64a42) in #8. Either that, or #7.

We should consolidate these menus into a single one.

**Comment by quicksketch** [comment]
They're different pieces of functionality, the top level "Development" item isn't Configuration, they're utility tools. Perhaps we should rename the top level link from "Development" to "Devel Tools" to make it clear it's something different?

**Comment by yorkshire-pudding** [comment]
I came across this today and was convinced something is wrong.
![chrome_qbj2gZ29fs](https://user-images.githubusercontent.com/20357797/203590140-613471fb-2b5a-4405-a6a0-63d49219736b.gif)

Why do we have 2 links for 'Devel settings'?  When you click on Development > Devel settings the path shows Configuration as being the parent, which is confusing.  If as @quicksketch suggests, the two are different, and Development perhaps should be Devel Tools, then we should perhaps take Devel Settings out of Development to reduce confusion.

I do think Devel tools would be clearer.

**Comment by jenlampton** [comment]
"Devel tools" it is. Committeed to 1.x and will be in the next release.
