### ISSUE TITLE
"Parameter must be an array or an object that implements Countable"

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/devel#44]
I get this warning every time I use `dpm()`:

> Warning: count(): Parameter must be an array or an object that implements Countable in dprint_r() (line 1697 of /[SNIP]/modules/devel/devel.module).

Researched it and it's because in PHP v7.2.0 "`count()` will now yield a warning on invalid countable types passed to the `array_or_countable` parameter." ([source](https://www.php.net/manual/en/function.count.php#refsect1-function.count-changelog)).

Ideal solution would be to simply check [`is_countable()`](https://www.php.net/manual/en/function.is-countable.php) first, but it's only available in PHP >= v7.3.0. So instead, based on a comment on that page, I've made a PR that checks via a polyfill (and fixes the warnings).

**Comment by klonos** [comment]
This is the respective issue as https://www.drupal.org/project/devel/issues/2959508

@BWPanda thanks for the research and finding that polyfill as a more future-proof solution 👍 ...we should include the rest of the changes that went in with https://git.drupalcode.org/project/devel/commit/bd4061f though. I have amended your PR to do just that. I hope that's OK.

**Comment by ghost** [comment]
Sure, I added some review questions though...

**Comment by klonos** [comment]
@BWPanda I don't see any comments in the PR.

**Comment by klonos** [comment]
This is currently blocked on https://github.com/backdrop-contrib/devel/pull/58

**Comment by alanmels** [comment]
@klonos, Thanks for pointing the previously reported issue. Next time I will search the issues better to avoid duplicated work.

I am on https://github.com/backdrop-contrib/devel/pull/45/files now I have some additional notes which I'll put as code review.

**Comment by alanmels** [comment]
Guys, would be nice to get this resolved as we are using the module on daily basis.

**Comment by klonos** [comment]
@alanmels @BWPanda I have updated the PR. Can you please have a look.

**Comment by alanmels** [comment]
> @alanmels @BWPanda I have updated the PR. Can you please have a look.

I've just tested and everything seems to be working just fine. Thanks!

**Comment by klonos** [comment]
I have now merged the PR. @alanmels @BWPanda please test 1.x for a few days, and if happy with it, I will create a release (please nudge me on Gitter 😉). Thank you both on helping out with this 👍

**Comment by kktsvetkov** [comment]
Can you also look into upgrading Krumo, I think this is fixed in https://github.com/kktsvetkov/krumo/releases/tag/0.4.1 ?
