### ISSUE TITLE
Notice: Trying to get property of non-object in {closure}()

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#48]
When trying to generate taxonomy terms for (also devel-generated) vocabularies, I get this notice, repeated multiple times; independently of number of vocabularies and/or number of terns trying to generate:

```
- Notice: Trying to get property of non-object in {closure}()
  (line 1161 of /core/modules/taxonomy/taxonomy.module).
```

...followed by this:

```
- Notice: Trying to get property of non-object in devel_generate_terms()
  (line 221 of /modules/devel/devel_generate/devel_generate.inc).
- EntityMalformedException: Missing bundle property on entity
  of type taxonomy_term. in entity_extract_ids()
  (line 323 of /core/modules/entity/entity.module).
- EntityStorageException: Missing bundle property on entity
  of type taxonomy_term. in EntityDatabaseStorageController->save()
  (line 552 of /core/modules/entity/entity.controller.inc).
```

Some terms are being generated, but not all. A random number each time; different for each vocabulary.

**Comment by quicksketch** [comment]
Thanks @klonos! I found out that we were sometimes passing in a vocabulary name of `NULL`, which caused this problem. But it only happens literally randomly for each term created. This should be fixed in ba01e0b.
