### ISSUE TITLE
ddebug_backtrace() not working for me

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/devel#5]
I am not getting ddebug_backtrace() to produce any output, although trying it in a way that is successful in Drupal 7. Am I doing something wrong or is it not working yet?

**Comment by quicksketch** [comment]
Hi @Graham-72! I've never tried that function, so there's a good chance it's not working at the moment. In the mean time, you could use `dsm(debug_backtrace())`.

**Comment by Graham-72** [comment]
Thanks @quicksketch , I have now successfully used dsm(debug_backtrace()) and also print_r(debug_backtrace()) where dsm() wasn't producing visible output.

**Comment by ghost** [comment]
I found the issue cause : it's about different coding of “error_level” between drupal and backdrop.
Line 1780 of devel.module : 
`if (config_get('system.core', 'error_level') >= 1) {`
If you `dpm('error_level:'.config_get('system.core', 'error_level'));`, it shows “all”
So a quick and dirty : 
`if (config_get('system.core', 'error_level') == 'all') {`
restores ddebug_backtrace() full functionality

**Comment by quicksketch** [comment]
Nice one @gifad! I'll fix this and make a new bugfix release.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/devel/commit/cbf9328d02b6a130b9db1b560359767b001a7231.
