### ISSUE TITLE
Devel generate -> Fatal error on content type Forum

### ISSUE THREAD

**Issue by Drupaldise** [backdrop-contrib/devel#6]
I am not sure if this is to devel or to the forum module related.
But when I try to generate content for forum topics, the following error is shown:
![mozilla firefox 2015-04-13 16-14-48](https://cloud.githubusercontent.com/assets/2930705/7117343/45415068-e1f8-11e4-911c-ebe2dbf4847c.jpg)

**Comment by quicksketch** [comment]
Thanks @Drupaldise. I think it may be a combination of issues. Core has a bug that I encountered recently. I filed an issue at https://github.com/backdrop/backdrop-issues/issues/866. The core bug is only an error in the error-handling however, so there's an additional problem that triggers it in the first place.

**Comment by quicksketch** [comment]
This problem is still occurring. Now that the core issue has been fixed, we get a more descriptive error message:

```
EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sticky' at row 1 in NodeStorageController->save() (line 304 of /home/nate/Sites/backdrop/core/modules/node/node.entity.inc).
```

So looks like we must be generating a node with an invalid option for "sticky", which should be 0 or 1, not an empty string.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/devel/commit/641bee02b422993b8b53c5c1c545f00ba0c6e81d. Thanks for reporting @Drupaldise!
