### ISSUE TITLE
move link field devel gernerate capabilities to the devel module

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/devel#8]
per https://github.com/backdrop/backdrop-issues/issues/240 we moved the `link` module to backdrop core.  As part of the refactor we should move the `link.devel_generate.inc` capabilities to this module (`devel`).

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/devel/commit/832883c277a59f7348526a3418347a5478ad1eb8. Thanks!
