### ISSUE TITLE
Include date.devel_generate.inc from Date contrib module.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#9]
In https://github.com/backdrop/backdrop-issues/issues/478 where we're getting date field into core, certain things changed or got (re)moved. One of these things is `date.devel_generate.inc`. So, if Devel is to support node generation when the node includes a date field, we need to include that.

**Comment by docwilmot** [comment]
core doesnt usually have contrib support code built in.

Devel should start including code to support core date, not vice versa.

**Comment by klonos** [comment]
> core doesnt usually have contrib support code built in.

Precisely, that's why @quicksketch is [removing things from Date contrib](https://github.com/backdrop/backdrop-issues/issues/478#issuecomment-136296582) before getting it in core.

> Devel should start including code to support core date, not vice versa.

Exactly. That's why perhaps we should get the code that was removed from `date.devel_generate.inc` into a `date.devel_generate.inc`. Right?

**Comment by klonos** [comment]
...from the list of Nate's comment:

> - ...
> - Removed date.devel_generate.inc, move to Devel module.
> - ...

So this issue here serves as a todo.

**Comment by docwilmot** [comment]
Ignore me. Thought this was backdrop issue queue. Oops

**Comment by quicksketch** [comment]
Copying this right from contrib seemed to work perfectly, only needing to adjust `DateObject` into `BackdropDateTime`. Fixed in https://github.com/backdrop-contrib/devel/commit/90820ffa6f6c99db5deeba8662e439afee839521.
