### ISSUE TITLE
Make the xhprof location description more explicit

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/devel#91]
Per original issue on https://www.drupal.org/project/devel/issues/1670686:

> I failed at settings this up as I tried "/usr/share/php/xhprof_lib/utils/", and "/usr/share/php/xhprof_lib/", but not "/usr/share/php/", which I only figured out after looking at the devel source.

**Comment by quicksketch** [comment]
Thanks @alanmels! As part of https://github.com/backdrop-contrib/devel/pull/64 we're removing XHProf from Devel, I put my explanation there in the PR.

I use XHProf (or Tideways) still regularly and I think it's a very valuable thing for us to support within Backdrop, but getting Tideways working with the XHProf library to inspect the reports is a serious pain. We should port the XHProf module from Drupal contrib into a module named "Tideways" and support only that extension. At this point the original XHProf extension is quite dead.
