### ISSUE TITLE
Notice: Undefined variable: _recursion_marker in krumo::_vars() (line 1018 of ..devel/lib/krumo/class.krumo.php).

### ISSUE THREAD

**Issue by nickonom** [backdrop-contrib/devel#98]
Hello,

To replicate the error, just go to `/node/2/devel` and `/admin/reports/dblog` will be filled with error messages as:

```
Notice: Undefined variable: _recursion_marker in krumo::_vars() (line 1018 of /var/www/docroot/modules/devel/lib/krumo/class.krumo.php).
```

**Comment by alanmels** [comment]
The search_krumo module has to be enabled to replicate the issue.

**Comment by ghost** [comment]
PR looks good to me. Can @quicksketch merge and make a new release, or can a @backdrop-contrib/bug-squad member?

**Comment by jenlampton** [comment]
I put on my bug-squad hat and merged the PR, but we aren't authorized to make a new release.
